name: Deploy FastAPI Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t your-dockerhub-username/fastapi-app:latest .

    - name: Push Docker image
      run: |
        docker push your-dockerhub-username/fastapi-app:latest

    - name: SSH into remote host and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.30.44
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker pull your-dockerhub-username/fastapi-app:latest
          docker run -d --name fastapi-app -p 8686:8000 your-dockerhub-username/fastapi-app:latest
